workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install

      - name: Run Expo Prebuild
        script: | 
          npx expo prebuild --platform android

      - name: Build Android APK
        script: | 
          cd android
          # Correctif critique pour la version de Gradle
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 8.1.1 --distribution-type all
          
          # Compilation
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
