workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install Dependencies (Safe Mode)
        script: | 
          # 1. Nettoyage radical
          rm -rf node_modules
          rm -f package-lock.json
          
          # 2. Installation forcée pour contourner les conflits mineurs
          npm install --legacy-peer-deps
          
          # 3. Alignement final sur Expo 51
          npx expo install --fix

      - name: Expo Prebuild
        script: | 
          # Génération propre du projet Android
          npx expo prebuild --platform android --clean

      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          # Expo 51 sur M2 est compatible par défaut, on lance le build standard
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
