workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install Dependencies
        script: | 
          # On nettoie pour éviter les conflits cachés
          rm -rf node_modules
          rm -f package-lock.json
          
          # LE SECRET EST ICI : --legacy-peer-deps
          # Cela force l'installation malgré le conflit de version du plugin WebRTC
          npm install --legacy-peer-deps
          
          # On laisse Expo aligner les versions des librairies principales
          npx expo install --fix

      - name: Expo Prebuild
        script: | 
          # Génération propre du projet Android
          npx expo prebuild --platform android --clean

      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          # Avec Expo 51, plus besoin de hacks Gradle, ça marche nativement
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
