workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install Dependencies
        script: | 
          # Nettoyage préventif
          rm -rf node_modules
          rm -f package-lock.json
          
          # Installation propre
          npm install
          
          # S'assure que les versions sont compatibles Expo 50
          npx expo install --fix

      - name: Expo Prebuild
        script: | 
          # Génération des dossiers natifs
          npx expo prebuild --platform android --clean

      - name: Build Android APK (Gradle 8.2 fix)
        script: | 
          cd android
          
          # FIX CRITIQUE : On impose Gradle 8.2 (Version Goldilocks pour Expo 50)
          # Ni trop vieux (plante pas les plugins), ni trop récent (plante pas 'release')
          sed -i '' 's/distributionUrl=.*$/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.2-all.zip/g' gradle/wrapper/gradle-wrapper.properties
          
          chmod +x gradlew
          
          # On nettoie et on compile
          ./gradlew clean assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
