workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install

      - name: Run Expo Prebuild
        script: | 
          npx expo prebuild --platform android

      - name: Build Android APK (Force Gradle 8.1.1)
        script: | 
          cd android
          
          # METHODE FORTE : On réécrit le fichier de config pour imposer Gradle 8.1.1
          # Cela empêche le téléchargement automatique de la version 8.3 qui fait planter le build
          sed -i '' 's/distributionUrl=.*$/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.1.1-all.zip/g' gradle/wrapper/gradle-wrapper.properties
          
          # Vérification (pour les logs)
          echo "Vérification de la version forcée :"
          cat gradle/wrapper/gradle-wrapper.properties
          
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
