workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install & Fix Dependencies
        script: | 
          # Installe les paquets de base
          npm install
          
          # COMMANDE MAGIQUE : Aligne toutes les versions des libs sur le standard Expo 50
          # Cela corrige les bugs de compatibilité Gradle/Java
          npx expo install --fix

      - name: Expo Prebuild (Clean)
        script: | 
          # Génère le projet Android en partant de zéro (--clean)
          npx expo prebuild --platform android --clean

      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          
          # Nettoyage préalable pour éviter les résidus de l'ancien build
          ./gradlew clean
          
          # Compilation standard (on laisse Expo gérer la version de Gradle)
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
