workflows:
  android-debug:
    name: ComTac v14 Android (APK Debug)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install Dependencies
        script: | 
          # On supprime les vieux verrous pour forcer la mise à jour
          rm -f package-lock.json
          npm install
          
          # Cette commande va aligner toutes les versions sur le SDK 51
          npx expo install --fix

      - name: Expo Prebuild
        script: | 
          # On génère le projet natif proprement
          npx expo prebuild --platform android --clean

      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          # Plus besoin de forcer une version, Expo 51 gère Gradle 8.2+ nativement
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
